#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# Hermes Multi-User Deployment Setup
# ============================================================================
# Reads config.yml and generates a complete deployment:
#   - docker-compose.yml
#   - .env with API keys
#   - Per-user workspaces and .mcp.json
#   - Mimir seed data (if enabled)
#   - Host-side hermes wrapper scripts
#
# Usage:
#   ./setup.sh              # Interactive (prompts for deploy location)
#   ./setup.sh /path/to/dir # Non-interactive
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PARSER="$SCRIPT_DIR/parse_config.py"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}==>${NC} $1"; }
warn()  { echo -e "${YELLOW}==>${NC} $1"; }
error() { echo -e "${RED}==>${NC} $1" >&2; }

# ── Phase 1: Determine deploy location ──────────────────────────────────────

if [ -n "${1:-}" ]; then
    DEPLOY_DIR="$1"
else
    read -rp "Deploy location [${HOME}/hermes]: " DEPLOY_DIR
    DEPLOY_DIR="${DEPLOY_DIR:-${HOME}/hermes}"
fi

DEPLOY_DIR="$(realpath -m "$DEPLOY_DIR")"
info "Deploy location: $DEPLOY_DIR"

# ── Phase 2: Initialize deploy directory ────────────────────────────────────

mkdir -p "$DEPLOY_DIR/build" "$DEPLOY_DIR/data/shared/claude-auth" \
         "$DEPLOY_DIR/data/shared/claude-settings"

# Copy build files
cp "$SCRIPT_DIR/Dockerfile" "$DEPLOY_DIR/build/Dockerfile"
cp "$SCRIPT_DIR/entrypoint.sh" "$DEPLOY_DIR/build/entrypoint.sh"
cp "$SCRIPT_DIR/hermes.sh" "$DEPLOY_DIR/build/hermes.sh"
chmod +x "$DEPLOY_DIR/build/entrypoint.sh"

# Copy config if first run
if [ ! -f "$DEPLOY_DIR/config.yml" ]; then
    cp "$SCRIPT_DIR/config.yml.example" "$DEPLOY_DIR/config.yml"
    warn "Created config.yml — edit it now, then re-run setup.sh"
    warn "File: $DEPLOY_DIR/config.yml"
    exit 0
fi

# ── Phase 3: Parse config ───────────────────────────────────────────────────

CONFIG="$DEPLOY_DIR/config.yml"
info "Reading config from $CONFIG"

MIMIR_ENABLED=$(python3 "$PARSER" "$CONFIG" mimir.enabled)
MIMIR_PORT=$(python3 "$PARSER" "$CONFIG" mimir.port)
USER_IDS=$(python3 "$PARSER" "$CONFIG" user_ids)
USERS_JSON=$(python3 "$PARSER" "$CONFIG" users)
SCOPES_JSON=$(python3 "$PARSER" "$CONFIG" scopes)

info "Mimir: $MIMIR_ENABLED"
info "Users: $(echo $USER_IDS | sed 's/ /, /g')"

# ── Phase 4: Generate API keys (.env) ───────────────────────────────────────

ENV_FILE="$DEPLOY_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
    echo "# Generated by setup.sh — API keys and ports" > "$ENV_FILE"
    echo "MIMIR_PORT=$MIMIR_PORT" >> "$ENV_FILE"
    echo "" >> "$ENV_FILE"
fi

for user_id in $USER_IDS; do
    KEY_VAR="API_KEY_$(echo "$user_id" | tr '[:lower:]' '[:upper:]')"
    if ! grep -q "^${KEY_VAR}=" "$ENV_FILE" 2>/dev/null; then
        API_KEY=$(python3 -c "import uuid; print(uuid.uuid4())")
        echo "${KEY_VAR}=${API_KEY}" >> "$ENV_FILE"
        info "Generated API key for $user_id"
    fi
done

# Source the .env for variable access
set -a
source "$ENV_FILE"
set +a

# ── Phase 5: Generate docker-compose.yml ────────────────────────────────────

COMPOSE_FILE="$DEPLOY_DIR/docker-compose.yml"
info "Generating docker-compose.yml"

# Header
cat > "$COMPOSE_FILE" << 'HEADER'
# Generated by setup.sh — do not edit manually.
# Re-run setup.sh to regenerate after config.yml changes.

networks:
  hermes-net:
    driver: bridge

services:
HEADER

# Mimir service (if enabled)
if [ "$MIMIR_ENABLED" = "true" ]; then
    cat >> "$COMPOSE_FILE" << MIMIR
  mimir:
    image: mimir-mcp
    container_name: mimir
    networks: [hermes-net]
    restart: unless-stopped
    ports: ["\${MIMIR_PORT:-$MIMIR_PORT}:8100"]
    volumes:
      - ./data/mimir/data:/data
      - ./data/mimir/seed.sql:/data/seed.sql:ro
    environment:
      - MIMIR_DB_PATH=/data/mimir.db
      - MIMIR_SEED_FILE=/data/seed.sql
      - MIMIR_PORT=8100

MIMIR
fi

# User services
for user_id in $USER_IDS; do
    KEY_VAR="API_KEY_$(echo "$user_id" | tr '[:lower:]' '[:upper:]')"
    cat >> "$COMPOSE_FILE" << USER
  ${user_id}-hermes:
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: ${user_id}-hermes
    networks: [hermes-net]
    restart: unless-stopped
    volumes:
      - ./data/users/${user_id}/workspace:/home/user/hermes
      - ./data/users/${user_id}/claude-state:/home/user/.claude
      - ./data/shared/claude-auth:/opt/hermes/auth:ro
      - ./data/shared/claude-settings:/opt/hermes/settings:ro
    environment:
      - USER_NAME=${user_id}
    stdin_open: true
    tty: true

USER
done

# ── Phase 6: Create per-user workspaces ─────────────────────────────────────

for user_id in $USER_IDS; do
    USER_DIR="$DEPLOY_DIR/data/users/$user_id"
    WORKSPACE="$USER_DIR/workspace"

    if [ -d "$WORKSPACE/.claude" ]; then
        info "Workspace for $user_id already exists — skipping"
    else
        info "Creating workspace for $user_id"
        mkdir -p "$WORKSPACE" "$USER_DIR/claude-state"

        # Copy template files
        cp -r "$TEMPLATE_DIR/.claude" "$WORKSPACE/.claude"
        cp -r "$TEMPLATE_DIR/state" "$WORKSPACE/state"
        cp "$TEMPLATE_DIR/.env.example" "$WORKSPACE/.env.example"
        mkdir -p "$WORKSPACE/sessions" "$WORKSPACE/reports" "$WORKSPACE/content" \
                 "$WORKSPACE/meetings" "$WORKSPACE/research" "$WORKSPACE/decisions"

        # Generate personalized CLAUDE.md
        USER_NAME=$(python3 "$PARSER" "$CONFIG" "user.$user_id.name")
        sed "s/\[Your Name\]/$USER_NAME/g" "$TEMPLATE_DIR/CLAUDE.md" > "$WORKSPACE/CLAUDE.md"
    fi

    # Generate .mcp.json (if Mimir enabled) — always update, even for existing workspaces
    if [ "$MIMIR_ENABLED" = "true" ]; then
        KEY_VAR="API_KEY_$(echo "$user_id" | tr '[:lower:]' '[:upper:]')"
        API_KEY="${!KEY_VAR}"
        sed -e "s/%%MIMIR_PORT%%/$MIMIR_PORT/g" \
            -e "s/%%API_KEY%%/$API_KEY/g" \
            "$SCRIPT_DIR/templates/mcp.json.tmpl" > "$USER_DIR/.mcp.json"
        # Copy into workspace for Claude Code to find
        cp "$USER_DIR/.mcp.json" "$WORKSPACE/.mcp.json"
    fi
done

# ── Phase 7: Generate Mimir seed data ───────────────────────────────────────

if [ "$MIMIR_ENABLED" = "true" ]; then
    SEED_FILE="$DEPLOY_DIR/data/mimir/seed.sql"
    mkdir -p "$DEPLOY_DIR/data/mimir/data"

    if [ ! -f "$SEED_FILE" ]; then
        info "Generating Mimir seed data"
        echo "-- Generated by setup.sh" > "$SEED_FILE"
        echo "" >> "$SEED_FILE"

        # Insert scopes
        echo "$SCOPES_JSON" | python3 -c "
import json, sys
for s in json.load(sys.stdin):
    sid = s['id'].replace(\"'\", \"''\")
    name = s['name'].replace(\"'\", \"''\")
    desc = s.get('description', '').replace(\"'\", \"''\")
    print(f\"INSERT INTO scopes (id, name, description) VALUES ('{sid}', '{name}', '{desc}');\")
" >> "$SEED_FILE"
        echo "" >> "$SEED_FILE"

        # Insert users
        for user_id in $USER_IDS; do
            KEY_VAR="API_KEY_$(echo "$user_id" | tr '[:lower:]' '[:upper:]')"
            API_KEY="${!KEY_VAR}"
            USER_NAME=$(python3 "$PARSER" "$CONFIG" "user.$user_id.name")
            IS_ADMIN=$(python3 "$PARSER" "$CONFIG" "user.$user_id.admin")
            IS_ADMIN_SQL="FALSE"
            [ "$IS_ADMIN" = "True" ] && IS_ADMIN_SQL="TRUE"

            echo "INSERT INTO users (id, name, is_admin, api_key) VALUES ('$user_id', '$USER_NAME', $IS_ADMIN_SQL, '$API_KEY');" >> "$SEED_FILE"
        done
        echo "" >> "$SEED_FILE"

        # Insert scope memberships
        echo "$USERS_JSON" | python3 -c "
import json, sys
for u in json.load(sys.stdin):
    for scope in u.get('scopes', []):
        print(f\"INSERT INTO scope_members (scope_id, user_id) VALUES ('{scope}', '{u['id']}');\")
" >> "$SEED_FILE"
        echo "" >> "$SEED_FILE"

        # Insert activity cursors
        for user_id in $USER_IDS; do
            echo "INSERT INTO activity_cursor (user_id, last_seen_history_id) VALUES ('$user_id', 0);" >> "$SEED_FILE"
        done

        info "Seed file: $SEED_FILE"
    fi
fi

# ── Phase 8: Claude auth ────────────────────────────────────────────────────

AUTH_DIR="$DEPLOY_DIR/data/shared/claude-auth"
if [ ! "$(ls -A "$AUTH_DIR" 2>/dev/null)" ]; then
    echo ""
    warn "Claude Code auth not yet configured."
    warn "Copy your credentials to share with all containers:"
    warn "  cp ~/.claude/.credentials.json $AUTH_DIR/"
    warn ""
    warn "Or skip — users can run 'claude login' inside their containers."
    echo ""
    if [ -t 0 ]; then
        read -rp "Press Enter to continue without auth, or Ctrl+C to stop and copy first... "
    else
        warn "Non-interactive mode — continuing without auth."
    fi
fi

# ── Phase 9: Generate host wrapper scripts ──────────────────────────────────

for user_id in $USER_IDS; do
    WRAPPER="$DEPLOY_DIR/data/users/$user_id/hermes-wrapper.sh"
    sed "s/%%USER_ID%%/$user_id/g" \
        "$SCRIPT_DIR/templates/host-wrapper.sh.tmpl" > "$WRAPPER"
    info "Host wrapper for $user_id: source $WRAPPER"
done

# ── Phase 10: Build and start ───────────────────────────────────────────────

if command -v docker &>/dev/null && docker compose version &>/dev/null; then
    info "Building containers..."
    cd "$DEPLOY_DIR"
    docker compose build

    info "Starting all containers..."
    docker compose up -d
else
    warn "Docker not available — skipping build and start."
    warn "Run 'docker compose up -d' from $DEPLOY_DIR when ready."
fi

# ── Phase 11: Initialize git ────────────────────────────────────────────────

if [ ! -d "$DEPLOY_DIR/.git" ]; then
    cd "$DEPLOY_DIR"
    cat > .gitignore << 'GITIGNORE'
.env
data/shared/claude-auth/
data/users/*/claude-state/
data/mimir/data/
GITIGNORE
    git init
    git add .
    git commit -m "Initial Hermes multi-user deployment"
fi

# ── Done ────────────────────────────────────────────────────────────────────

echo ""
info "Deployment ready at $DEPLOY_DIR"
echo ""
echo "  Containers:"
for user_id in $USER_IDS; do
    echo "    $user_id: docker exec -it ${user_id}-hermes tmux attach -t hermes"
done
if [ "$MIMIR_ENABLED" = "true" ]; then
    echo "    mimir: http://localhost:$MIMIR_PORT"
fi
echo ""
echo "  Add the 'hermes' shortcut to your shell:"
for user_id in $USER_IDS; do
    echo "    source $DEPLOY_DIR/data/users/$user_id/hermes-wrapper.sh"
done
echo ""
echo "  Commands:"
echo "    hermes            — AI assistant (tmux + Claude Code)"
echo "    hermes <name>     — named Claude Code session"
echo "    hermes shell      — plain bash shell in container"
echo "    hermes list       — show active sessions"
echo ""
echo "  Remote access (from another machine):"
echo "    Copy the wrapper script and set HERMES_REMOTE=\"user@this-host\""
echo ""
echo "  To stop:  cd $DEPLOY_DIR && docker compose down"
echo "  To start: cd $DEPLOY_DIR && docker compose up -d"
echo ""
