#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# Hermes Multi-User Deployment Setup
# ============================================================================
# Two modes:
#
#   Full deploy — reads config.yml and generates a complete deployment:
#     ./setup.sh              # Interactive (prompts for deploy location)
#     ./setup.sh /path/to/dir # Non-interactive
#
#   Connect only — install just the wrapper for remote access:
#     ./setup.sh --connect user@host --user jimmy [--port 22] [--key ~/.ssh/id]
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PARSER="$SCRIPT_DIR/parse_config.py"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}==>${NC} $1"; }
warn()  { echo -e "${YELLOW}==>${NC} $1"; }
error() { echo -e "${RED}==>${NC} $1" >&2; }

# ── Connect mode: install remote wrapper only ─────────────────────────────

if [ "${1:-}" = "--connect" ]; then
    REMOTE_HOST=""
    CONNECT_USER=""
    SSH_PORT=""
    SSH_KEY=""

    shift
    while [ $# -gt 0 ]; do
        case "$1" in
            --user)  CONNECT_USER="$2"; shift 2 ;;
            --port)  SSH_PORT="$2"; shift 2 ;;
            --key)   SSH_KEY="$2"; shift 2 ;;
            *)
                if [ -z "$REMOTE_HOST" ]; then
                    REMOTE_HOST="$1"; shift
                else
                    error "Unknown argument: $1"; exit 1
                fi
                ;;
        esac
    done

    if [ -z "$REMOTE_HOST" ] || [ -z "$CONNECT_USER" ]; then
        echo "Usage: $0 --connect user@host --user container-user [--port 22] [--key ~/.ssh/id]"
        echo ""
        echo "  user@host       SSH target (e.g., jimmy@vps.example.com)"
        echo "  --user NAME     Container user ID (e.g., jimmy)"
        echo "  --port PORT     SSH port (default: 22)"
        echo "  --key PATH      SSH key path (default: ssh default)"
        exit 1
    fi

    CONTAINER="${CONNECT_USER}-hermes"
    WRAPPER_TEMPLATE="$SCRIPT_DIR/templates/host-wrapper.sh.tmpl"

    if [ ! -f "$WRAPPER_TEMPLATE" ]; then
        error "Template not found: $WRAPPER_TEMPLATE"
        exit 1
    fi

    # Detect shell and choose install location
    CURRENT_SHELL=$(basename "${SHELL:-bash}")
    if [ "$CURRENT_SHELL" = "fish" ]; then
        INSTALL_DIR="$HOME/.config/fish/conf.d"
        INSTALL_FILE="$INSTALL_DIR/hermes.fish"
        # Generate fish wrapper
        mkdir -p "$INSTALL_DIR"
        cat > "$INSTALL_FILE" << FISHEOF
# hermes — remote access to ${CONNECT_USER}'s Hermes AI assistant
# Generated by setup.sh --connect

function __hermes_exec
    set -l flags \$argv[1]
    set -e argv[1]
    set -l ssh_opts -t
    test -n "$SSH_PORT"; and set ssh_opts \$ssh_opts -p $SSH_PORT
    test -n "$SSH_KEY"; and set ssh_opts \$ssh_opts -i $SSH_KEY
    ssh \$ssh_opts $REMOTE_HOST docker exec \$flags $CONTAINER \$argv
end

function hermes
    set -l cmd \$argv[1]

    switch "\$cmd"
        case shell
            __hermes_exec -it bash -l
        case list
            __hermes_exec -i tmux list-windows -t hermes -F '  #{window_index}: #{window_name}' 2>/dev/null
            or echo 'No Hermes session running.'
        case ''
            __hermes_exec -it tmux attach -t hermes 2>/dev/null
            or __hermes_exec -it bash -lc hermes
        case '*'
            __hermes_exec -it bash -lc "hermes \$cmd"
    end
end
FISHEOF
        info "Installed fish wrapper: $INSTALL_FILE"
    else
        INSTALL_DIR="$HOME/.config/hermes"
        INSTALL_FILE="$INSTALL_DIR/wrapper.sh"
        mkdir -p "$INSTALL_DIR"

        # Generate bash wrapper from template
        sed -e "s/%%USER_ID%%/$CONNECT_USER/g" "$WRAPPER_TEMPLATE" > "$INSTALL_FILE"

        # Fill in SSH config
        sed -i "s|^HERMES_REMOTE=\"\"|HERMES_REMOTE=\"$REMOTE_HOST\"|" "$INSTALL_FILE"
        [ -n "$SSH_PORT" ] && sed -i "s|^HERMES_SSH_PORT=\"\"|HERMES_SSH_PORT=\"$SSH_PORT\"|" "$INSTALL_FILE"
        [ -n "$SSH_KEY" ] && sed -i "s|^HERMES_SSH_KEY=\"\"|HERMES_SSH_KEY=\"$SSH_KEY\"|" "$INSTALL_FILE"

        info "Installed bash wrapper: $INSTALL_FILE"

        # Add to shell config if not already sourced
        SHELL_RC="$HOME/.bashrc"
        [ -f "$HOME/.zshrc" ] && SHELL_RC="$HOME/.zshrc"
        SOURCE_LINE="source $INSTALL_FILE"
        if ! grep -qF "$SOURCE_LINE" "$SHELL_RC" 2>/dev/null; then
            echo "" >> "$SHELL_RC"
            echo "# Hermes remote wrapper" >> "$SHELL_RC"
            echo "$SOURCE_LINE" >> "$SHELL_RC"
            info "Added to $SHELL_RC"
        fi
    fi

    echo ""
    info "Connected to $REMOTE_HOST as $CONNECT_USER"
    echo ""
    echo "  hermes            — AI assistant (tmux + Claude Code)"
    echo "  hermes <name>     — named Claude Code session"
    echo "  hermes shell      — plain bash shell in container"
    echo "  hermes list       — show active sessions"
    echo ""
    echo "  Restart your shell or run: source $INSTALL_FILE"
    exit 0
fi

# ── Full deploy mode ──────────────────────────────────────────────────────

# ── Phase 1: Determine deploy location ──────────────────────────────────────

if [ -n "${1:-}" ]; then
    DEPLOY_DIR="$1"
else
    read -rp "Deploy location [${HOME}/hermes]: " DEPLOY_DIR
    DEPLOY_DIR="${DEPLOY_DIR:-${HOME}/hermes}"
fi

DEPLOY_DIR="$(realpath -m "$DEPLOY_DIR")"
info "Deploy location: $DEPLOY_DIR"

# ── Phase 2: Initialize deploy directory ────────────────────────────────────

mkdir -p "$DEPLOY_DIR/build" "$DEPLOY_DIR/data/shared/claude-auth" \
         "$DEPLOY_DIR/data/shared/claude-settings"

# Copy build files
cp "$SCRIPT_DIR/Dockerfile" "$DEPLOY_DIR/build/Dockerfile"
cp "$SCRIPT_DIR/entrypoint.sh" "$DEPLOY_DIR/build/entrypoint.sh"
cp "$SCRIPT_DIR/hermes.sh" "$DEPLOY_DIR/build/hermes.sh"
chmod +x "$DEPLOY_DIR/build/entrypoint.sh"

# Copy config if first run
if [ ! -f "$DEPLOY_DIR/config.yml" ]; then
    cp "$SCRIPT_DIR/config.yml.example" "$DEPLOY_DIR/config.yml"
    warn "Created config.yml — edit it now, then re-run setup.sh"
    warn "File: $DEPLOY_DIR/config.yml"
    exit 0
fi

# ── Phase 3: Parse config ───────────────────────────────────────────────────

CONFIG="$DEPLOY_DIR/config.yml"
info "Reading config from $CONFIG"

MIMIR_ENABLED=$(python3 "$PARSER" "$CONFIG" mimir.enabled)
MIMIR_PORT=$(python3 "$PARSER" "$CONFIG" mimir.port)
USER_IDS=$(python3 "$PARSER" "$CONFIG" user_ids)
USERS_JSON=$(python3 "$PARSER" "$CONFIG" users)
SCOPES_JSON=$(python3 "$PARSER" "$CONFIG" scopes)

info "Mimir: $MIMIR_ENABLED"
info "Users: $(echo $USER_IDS | sed 's/ /, /g')"

# ── Phase 4: Generate API keys (.env) ───────────────────────────────────────

ENV_FILE="$DEPLOY_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
    echo "# Generated by setup.sh — API keys and ports" > "$ENV_FILE"
    echo "MIMIR_PORT=$MIMIR_PORT" >> "$ENV_FILE"
    echo "" >> "$ENV_FILE"
fi

for user_id in $USER_IDS; do
    KEY_VAR="API_KEY_$(echo "$user_id" | tr '[:lower:]' '[:upper:]')"
    if ! grep -q "^${KEY_VAR}=" "$ENV_FILE" 2>/dev/null; then
        API_KEY=$(python3 -c "import uuid; print(uuid.uuid4())")
        echo "${KEY_VAR}=${API_KEY}" >> "$ENV_FILE"
        info "Generated API key for $user_id"
    fi
done

# Source the .env for variable access
set -a
source "$ENV_FILE"
set +a

# ── Phase 5: Generate docker-compose.yml ────────────────────────────────────

COMPOSE_FILE="$DEPLOY_DIR/docker-compose.yml"
info "Generating docker-compose.yml"

# Header
cat > "$COMPOSE_FILE" << 'HEADER'
# Generated by setup.sh — do not edit manually.
# Re-run setup.sh to regenerate after config.yml changes.

networks:
  hermes-net:
    driver: bridge

services:
HEADER

# Mimir service (if enabled)
if [ "$MIMIR_ENABLED" = "true" ]; then
    cat >> "$COMPOSE_FILE" << MIMIR
  mimir:
    image: mimir-mcp
    container_name: mimir
    networks: [hermes-net]
    restart: unless-stopped
    ports: ["\${MIMIR_PORT:-$MIMIR_PORT}:8100"]
    volumes:
      - ./data/mimir/data:/data
      - ./data/mimir/seed.sql:/data/seed.sql:ro
    environment:
      - MIMIR_DB_PATH=/data/mimir.db
      - MIMIR_SEED_FILE=/data/seed.sql
      - MIMIR_PORT=8100

MIMIR
fi

# User services
for user_id in $USER_IDS; do
    KEY_VAR="API_KEY_$(echo "$user_id" | tr '[:lower:]' '[:upper:]')"
    cat >> "$COMPOSE_FILE" << USER
  ${user_id}-hermes:
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: ${user_id}-hermes
    networks: [hermes-net]
    restart: unless-stopped
    volumes:
      - ./data/users/${user_id}/workspace:/home/user/hermes
      - ./data/users/${user_id}/claude-state:/home/user/.claude
      - ./data/shared/claude-auth:/opt/hermes/auth:ro
      - ./data/shared/claude-settings:/opt/hermes/settings:ro
    environment:
      - USER_NAME=${user_id}
    stdin_open: true
    tty: true

USER
done

# ── Phase 6: Create per-user workspaces ─────────────────────────────────────

for user_id in $USER_IDS; do
    USER_DIR="$DEPLOY_DIR/data/users/$user_id"
    WORKSPACE="$USER_DIR/workspace"

    if [ -d "$WORKSPACE/.claude" ]; then
        info "Workspace for $user_id already exists — skipping"
    else
        info "Creating workspace for $user_id"
        mkdir -p "$WORKSPACE" "$USER_DIR/claude-state"

        # Copy template files
        cp -r "$TEMPLATE_DIR/.claude" "$WORKSPACE/.claude"
        cp -r "$TEMPLATE_DIR/state" "$WORKSPACE/state"
        cp "$TEMPLATE_DIR/.env.example" "$WORKSPACE/.env.example"
        mkdir -p "$WORKSPACE/sessions" "$WORKSPACE/reports" "$WORKSPACE/content" \
                 "$WORKSPACE/meetings" "$WORKSPACE/research" "$WORKSPACE/decisions"

        # Generate personalized CLAUDE.md
        USER_NAME=$(python3 "$PARSER" "$CONFIG" "user.$user_id.name")
        sed "s/\[Your Name\]/$USER_NAME/g" "$TEMPLATE_DIR/CLAUDE.md" > "$WORKSPACE/CLAUDE.md"
    fi

    # Generate .mcp.json (if Mimir enabled) — always update, even for existing workspaces
    if [ "$MIMIR_ENABLED" = "true" ]; then
        KEY_VAR="API_KEY_$(echo "$user_id" | tr '[:lower:]' '[:upper:]')"
        API_KEY="${!KEY_VAR}"
        sed -e "s/%%MIMIR_PORT%%/$MIMIR_PORT/g" \
            -e "s/%%API_KEY%%/$API_KEY/g" \
            "$SCRIPT_DIR/templates/mcp.json.tmpl" > "$USER_DIR/.mcp.json"
        # Copy into workspace for Claude Code to find
        cp "$USER_DIR/.mcp.json" "$WORKSPACE/.mcp.json"
    fi
done

# ── Phase 7: Generate Mimir seed data ───────────────────────────────────────

if [ "$MIMIR_ENABLED" = "true" ]; then
    SEED_FILE="$DEPLOY_DIR/data/mimir/seed.sql"
    mkdir -p "$DEPLOY_DIR/data/mimir/data"

    if [ ! -f "$SEED_FILE" ]; then
        info "Generating Mimir seed data"
        echo "-- Generated by setup.sh" > "$SEED_FILE"
        echo "" >> "$SEED_FILE"

        # Insert scopes
        echo "$SCOPES_JSON" | python3 -c "
import json, sys
for s in json.load(sys.stdin):
    sid = s['id'].replace(\"'\", \"''\")
    name = s['name'].replace(\"'\", \"''\")
    desc = s.get('description', '').replace(\"'\", \"''\")
    print(f\"INSERT INTO scopes (id, name, description) VALUES ('{sid}', '{name}', '{desc}');\")
" >> "$SEED_FILE"
        echo "" >> "$SEED_FILE"

        # Insert users
        for user_id in $USER_IDS; do
            KEY_VAR="API_KEY_$(echo "$user_id" | tr '[:lower:]' '[:upper:]')"
            API_KEY="${!KEY_VAR}"
            USER_NAME=$(python3 "$PARSER" "$CONFIG" "user.$user_id.name")
            IS_ADMIN=$(python3 "$PARSER" "$CONFIG" "user.$user_id.admin")
            IS_ADMIN_SQL="FALSE"
            [ "$IS_ADMIN" = "True" ] && IS_ADMIN_SQL="TRUE"

            echo "INSERT INTO users (id, name, is_admin, api_key) VALUES ('$user_id', '$USER_NAME', $IS_ADMIN_SQL, '$API_KEY');" >> "$SEED_FILE"
        done
        echo "" >> "$SEED_FILE"

        # Insert scope memberships
        echo "$USERS_JSON" | python3 -c "
import json, sys
for u in json.load(sys.stdin):
    for scope in u.get('scopes', []):
        print(f\"INSERT INTO scope_members (scope_id, user_id) VALUES ('{scope}', '{u['id']}');\")
" >> "$SEED_FILE"
        echo "" >> "$SEED_FILE"

        # Insert activity cursors
        for user_id in $USER_IDS; do
            echo "INSERT INTO activity_cursor (user_id, last_seen_history_id) VALUES ('$user_id', 0);" >> "$SEED_FILE"
        done

        info "Seed file: $SEED_FILE"
    fi
fi

# ── Phase 8: Claude auth ────────────────────────────────────────────────────

AUTH_DIR="$DEPLOY_DIR/data/shared/claude-auth"
if [ ! "$(ls -A "$AUTH_DIR" 2>/dev/null)" ]; then
    echo ""
    warn "Claude Code auth not yet configured."
    warn "Copy your credentials to share with all containers:"
    warn "  cp ~/.claude/.credentials.json $AUTH_DIR/"
    warn ""
    warn "Or skip — users can run 'claude login' inside their containers."
    echo ""
    if [ -t 0 ]; then
        read -rp "Press Enter to continue without auth, or Ctrl+C to stop and copy first... "
    else
        warn "Non-interactive mode — continuing without auth."
    fi
fi

# ── Phase 9: Generate and install host wrapper scripts ────────────────────

CURRENT_SHELL=$(basename "${SHELL:-bash}")

for user_id in $USER_IDS; do
    # Generate both formats
    WRAPPER_SH="$DEPLOY_DIR/data/users/$user_id/hermes-wrapper.sh"
    WRAPPER_FISH="$DEPLOY_DIR/data/users/$user_id/hermes-wrapper.fish"
    sed "s/%%USER_ID%%/$user_id/g" \
        "$SCRIPT_DIR/templates/host-wrapper.sh.tmpl" > "$WRAPPER_SH"
    sed "s/%%USER_ID%%/$user_id/g" \
        "$SCRIPT_DIR/templates/host-wrapper.fish.tmpl" > "$WRAPPER_FISH"

    # Auto-install for the user running setup.sh
    if [ "$CURRENT_SHELL" = "fish" ]; then
        INSTALL_DIR="$HOME/.config/fish/conf.d"
        INSTALL_FILE="$INSTALL_DIR/hermes-${user_id}.fish"
        mkdir -p "$INSTALL_DIR"
        cp "$WRAPPER_FISH" "$INSTALL_FILE"
        info "Installed $user_id wrapper: $INSTALL_FILE"
    else
        SHELL_RC="$HOME/.bashrc"
        [ -f "$HOME/.zshrc" ] && SHELL_RC="$HOME/.zshrc"
        SOURCE_LINE="source $WRAPPER_SH"
        if ! grep -qF "$SOURCE_LINE" "$SHELL_RC" 2>/dev/null; then
            echo "" >> "$SHELL_RC"
            echo "# Hermes wrapper for $user_id" >> "$SHELL_RC"
            echo "$SOURCE_LINE" >> "$SHELL_RC"
        fi
        info "Installed $user_id wrapper in $SHELL_RC"
    fi
done

# ── Phase 10: Build and start ───────────────────────────────────────────────

if command -v docker &>/dev/null && docker compose version &>/dev/null; then
    info "Building containers..."
    cd "$DEPLOY_DIR"
    docker compose build

    info "Starting all containers..."
    docker compose up -d
else
    warn "Docker not available — skipping build and start."
    warn "Run 'docker compose up -d' from $DEPLOY_DIR when ready."
fi

# ── Phase 11: Initialize git ────────────────────────────────────────────────

if [ ! -d "$DEPLOY_DIR/.git" ]; then
    cd "$DEPLOY_DIR"
    cat > .gitignore << 'GITIGNORE'
.env
data/shared/claude-auth/
data/users/*/claude-state/
data/mimir/data/
GITIGNORE
    git init
    git add .
    git commit -m "Initial Hermes multi-user deployment"
fi

# ── Done ────────────────────────────────────────────────────────────────────

echo ""
info "Deployment ready at $DEPLOY_DIR"
echo ""
echo "  Containers:"
for user_id in $USER_IDS; do
    echo "    $user_id: docker exec -it ${user_id}-hermes tmux attach -t hermes"
done
if [ "$MIMIR_ENABLED" = "true" ]; then
    echo "    mimir: http://localhost:$MIMIR_PORT"
fi
echo ""
echo "  The 'hermes' command has been installed for your shell."
echo "  Restart your shell or run: exec $CURRENT_SHELL"
echo ""
echo "  Commands:"
echo "    hermes            — AI assistant (tmux + Claude Code)"
echo "    hermes <name>     — named Claude Code session"
echo "    hermes shell      — plain bash shell in container"
echo "    hermes list       — show active sessions"
echo ""
echo "  Remote access (from another machine):"
echo "    ./deploy/setup.sh --connect user@this-host --user <user-id>"
echo ""
echo "  To stop:  cd $DEPLOY_DIR && docker compose down"
echo "  To start: cd $DEPLOY_DIR && docker compose up -d"
echo ""
